### ISSUE TITLE
Run command for Mikrotik(json script(C#))

### ISSUE THREAD

**Issue by vinicius-s-guedes** [OneIdentity/SafeguardCustomPlatform#30]
Good afternoon, I have a problem with the Json code (C#), to run the commands in the terminal (Mikrotik).
The connection to SSH is established, but as soon as we try to run a command, the terminal returns empty.

And I would like to know, if you know any way to solve this problem, or would have a list of commands that could be used in this Json C#.

código que eu estava fazendo os test
https://versedbr-my.sharepoint.com/:i:/g/personal/vinicius_guedes_versed_net_br/ESjJG0tGl1hHl9DUqe5nqVsBOirud_55nJHHrSsPihU3gQ?e=QOz9LJ

**Comment by MiriamMcMahon** [comment]
@Vinicius-Santos-Guedes 
If I understand you correctly, you are sending the command ":put [/user print];" and then receiving the response                                                                            
 "[admin@MikroTik]>[admin@MikroTik]>" , rather than the expected output of the command.                                                                                                      The response looks like an input prompt, printed twice, which may indicate that the system has not executed the ":put" command yet.      
                                                                                                                                                                                                                                            I am not familiar with this particular platform, but here are some suggestions that may help:

**- Make sure you do a receive immediately after making the connection.**    
Most systems produce some sort of welcome message on first login. If you dont  consume all of this output before running your command, then the next receive will return this welcome text before the command output, and it will be harder to parse the output from the command.

**- Check if the system is waiting for a response.**    
 In some cases, the system may prompt for input on first login (e.g. password has expired), and the system is waiting for a response to this prompt before it can execute any commands.    
Try logging in interactively as the test user, and check exactly what the system does on first login, and ensure that your script handles this.

**- Make sure that each receive waits for long enough to do what you expect it to do.**    
A simple "Receive" will just do a single TCP receive and return the first output produced by the remote system (if any). It does not have any knowledge of what the remote system is doing.    
Every platform is different, and some are slower then others, so it often takes more than 1 receive to consume all the output produced when you send it a command to run.    
I recommend using the "Receive" properties https://github.com/OneIdentity/SafeguardCustomPlatform/wiki/Receive  to make sure you wait until **each** receive detects the output you expect before continuing (including the Receive you call on first login).   
                                                                                                                                                                                                                                           For example, if the ":put" command producess the following output :     
```
success              : "password:"
user not found error : "unknown user"
permission error     : "invalid command"
```
then wait for the command to output any of the these before continuing, and then check that the command was successful  :    
```
{
  "Receive": {
    "ConnectionObjectName": "ConnectSsh",                                                                                                                                                       
    "Buffer": "ReturnStatus"                                                                                                                                                                    
    "ExpectTimeout": 3000,                                                                                                                           
    "Append": true,                                                                                                                              
    "ExpectRegex": "(password:)|(invalid.*)|(unknown.*)"  
  }
},
{
  "Condition" : {
    "If" : "!Regex.IsMatch(ReturnStatus, \"password:\")",
    "Then" : {
      ..... handle error ....
    }
  }
}  
```
